// <auto-generated />
using System;
using ComercioLP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComercioLP.Migrations
{
    [DbContext(typeof(ComercioLPContext))]
    [Migration("20211101125000_OtherEntities")]
    partial class OtherEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComercioLP.Models.Departament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departament");
                });

            modelBuilder.Entity("ComercioLP.Models.VendasRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<double>("Quantidade")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("vendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("vendedorId");

                    b.ToTable("VendasRecord");
                });

            modelBuilder.Entity("ComercioLP.Models.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BaseSalario")
                        .HasColumnType("float");

                    b.Property<int?>("DepartamentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtNasc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentId");

                    b.ToTable("vendedor");
                });

            modelBuilder.Entity("ComercioLP.Models.VendasRecord", b =>
                {
                    b.HasOne("ComercioLP.Models.Vendedor", "vendedor")
                        .WithMany("Vend")
                        .HasForeignKey("vendedorId");

                    b.Navigation("vendedor");
                });

            modelBuilder.Entity("ComercioLP.Models.Vendedor", b =>
                {
                    b.HasOne("ComercioLP.Models.Departament", "Departament")
                        .WithMany("Vendedors")
                        .HasForeignKey("DepartamentId");

                    b.Navigation("Departament");
                });

            modelBuilder.Entity("ComercioLP.Models.Departament", b =>
                {
                    b.Navigation("Vendedors");
                });

            modelBuilder.Entity("ComercioLP.Models.Vendedor", b =>
                {
                    b.Navigation("Vend");
                });
#pragma warning restore 612, 618
        }
    }
}
